const state={meta:null,cache:new Map()};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const params=()=>new URLSearchParams(location.search);
const link=(obj={})=>{const u=new URL(location.href);u.search='';Object.entries(obj).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')u.searchParams.set(k,v)});return u.pathname+u.search};
async function loadMeta(){if(!state.meta){const r=await fetch('data/meta.json?v=20260711-ch32');if(!r.ok)throw Error('無法載入網站目錄');state.meta=await r.json()}return state.meta}
async function decodeB64Gzip(text){const bytes=Uint8Array.from(atob(text.trim()),c=>c.charCodeAt(0));if(!('DecompressionStream' in window))throw Error('瀏覽器版本過舊，請改用最新版 Chrome、Safari 或 Edge。');const ds=new DecompressionStream('gzip');return JSON.parse(await new Response(new Blob([bytes]).stream().pipeThrough(ds)).text())}
async function loadChapter(n){n=Number(n);if(state.cache.has(n))return state.cache.get(n);const meta=await loadMeta();const group=meta.chunks.find(x=>n>=x.start&&n<=x.end);if(!group)throw Error('找不到章節資料');if(!group.loaded){const r=await fetch(`data/${group.file}?v=20260711-ch32`);if(!r.ok)throw Error('無法載入章節');const chapters=await decodeB64Gzip(await r.text());chapters.forEach(c=>state.cache.set(Number(c.num),c));group.loaded=true}return state.cache.get(n)}
function setActive(ch){$$('.chapter-link').forEach(a=>a.classList.toggle('active',Number(a.dataset.chapter)===Number(ch)));$$('[data-link="home"]').forEach(a=>a.classList.toggle('active',!ch&&!params().get('page')&&!params().get('q')))}
function navHtml(meta){return meta.chapters.map(c=>`<a class="chapter-link" data-chapter="${c.num}" href="${link({chapter:c.num})}"><span class="chapter-no">${String(c.num).padStart(2,'0')}</span><span>${esc(c.title)}</span></a>`).join('')}
function breadcrumbs(parts=[]){$('#breadcrumb').innerHTML=`<a href="./">首頁</a>${parts.map(p=>` <span>›</span> ${p.href?`<a href="${p.href}">${esc(p.text)}</a>`:`<b>${esc(p.text)}</b>`}`).join('')}`}
function closeNav(){document.body.classList.remove('nav-open')}
function bindInternal(root=document){root.querySelectorAll('a[href^="?"] , a[href="./"]').forEach(a=>a.addEventListener('click',e=>{if(e.metaKey||e.ctrlKey||e.shiftKey)return;e.preventDefault();history.pushState({},'',a.getAttribute('href'));closeNav();route()}))}
function renderHome(meta){setActive();breadcrumbs();$('#view').innerHTML=`<section class="hero"><span class="eyebrow">社區藥事照護知識庫</span><h1>民眾藥安心<br>藥師藥關心</h1><p>將四十年社區藥局實務經驗整理成可搜尋、可逐篇閱讀的用藥照護網站。您可以從左側選擇章節，或直接搜尋藥名、症狀與常見問題。</p><div class="stats-row"><div class="stat"><b>${meta.total.toLocaleString()}</b><span>則完整問答</span></div><div class="stat"><b>${meta.chapters.length}</b><span>個用藥主題</span></div><div class="stat"><b>免費公開</b><span>手機與電腦皆可閱讀</span></div></div></section><section class="section"><div class="section-head"><div><h2>用藥照護章節</h2><p>點選後只顯示該章節的題目，不會跳離網站。</p></div></div><div class="chapter-grid">${meta.chapters.map(c=>`<a class="chapter-card" href="${link({chapter:c.num})}"><span class="chapter-badge">${String(c.num).padStart(2,'0')}</span><div><h3>${esc(c.title)}</h3><p>${c.count.toLocaleString()} 則問答</p></div><span class="go">›</span></a>`).join('')}</div></section>`;bindInternal($('#view'))}
function renderPage(name,meta){setActive();breadcrumbs([{text:name==='about'?'關於本網站':'用藥安全聲明'}]);$('#view').innerHTML=name==='about'?`<article class="info-page"><h1>關於本網站</h1><p>《民眾藥安心・藥師藥關心》源自長年社區藥局執業經驗，整理民眾在藥局常詢問的用藥與健康問題，並以數位知識庫方式公開分享。</p><h2>網站特色</h2><p>可依 ${meta.chapters.length} 個章節瀏覽、全文搜尋、逐篇閱讀及分享單篇網址；另提供大字模式，方便長輩與行動裝置閱讀。</p><h2>內容使用</h2><p>本網站提供一般健康教育資訊。個別病情與藥物選擇仍應由醫師及藥師依實際情況判斷。</p></article>`:`<article class="info-page"><h1>用藥安全聲明</h1><div class="notice"><strong>請勿只依網站內容自行停藥、加藥或調整劑量。</strong></div><p>病人的年齡、疾病、懷孕狀態、肝腎功能、過敏史及其他藥物都可能影響用藥方式。</p><h2>需要立即就醫的情況</h2><p>呼吸困難、意識改變、嚴重胸痛、疑似中風、嚴重過敏、持續大量出血、抽搐或疑似藥物過量，請立即就醫或聯絡當地緊急醫療服務。</p><h2>資訊優先順序</h2><p>實際使用藥品時，以目前藥袋標示、最新仿單、醫師醫囑及藥師個別指導為準。</p></article>`}
async function renderChapter(n){const meta=await loadMeta();const mc=meta.chapters.find(c=>c.num===Number(n));if(!mc)return renderHome(meta);setActive(n);breadcrumbs([{text:mc.title}]);$('#view').innerHTML='<div class="loading"><span></span>正在載入章節…</div>';const c=await loadChapter(n);let currentPage=Math.max(1,Number(params().get('p')||1));const per=30;function draw(filter=''){const key=filter.trim().toLowerCase();const items=key?c.items.filter(x=>(x.q+' '+x.a).toLowerCase().includes(key)):c.items;const pages=Math.max(1,Math.ceil(items.length/per));currentPage=Math.min(currentPage,pages);const part=items.slice((currentPage-1)*per,currentPage*per);$('#view').innerHTML=`<section class="page-title"><span class="chapter-index">第 ${String(c.num).padStart(2,'0')} 章</span><h1>${esc(c.title)}</h1><p>${c.count.toLocaleString()} 則完整問答・點選題目後進入單篇閱讀頁</p></section><div class="chapter-tools"><input id="chapterSearch" type="search" value="${esc(filter)}" placeholder="搜尋本章題目或答案"></div><div class="breadcrumb">${key?`找到 ${items.length.toLocaleString()} 則結果`:`第 ${currentPage} / ${pages} 頁`}</div><div class="question-list">${part.length?part.map(x=>`<a class="question-link" href="${link({chapter:c.num,question:x.id})}"><span class="question-id">${esc(x.id)}</span><span class="question-title">${esc(x.q)}</span><span class="question-arrow">›</span></a>`).join(''):`<div class="empty-state">本章沒有符合的結果。</div>`}</div>${!key&&pages>1?`<div class="pagination"><button id="prevPage" ${currentPage===1?'disabled':''}>上一頁</button><button class="active">${currentPage}</button><button id="nextPage" ${currentPage===pages?'disabled':''}>下一頁</button></div>`:''}`;bindInternal($('#view'));$('#chapterSearch').addEventListener('input',e=>{currentPage=1;draw(e.target.value)});$('#prevPage')?.addEventListener('click',()=>{currentPage--;draw();scrollTo({top:0,behavior:'smooth'})});$('#nextPage')?.addEventListener('click',()=>{currentPage++;draw();scrollTo({top:0,behavior:'smooth'})})}draw()}
async function renderQuestion(n,id){const c=await loadChapter(n);const idx=c.items.findIndex(x=>x.id===id);if(idx<0)return renderChapter(n);const x=c.items[idx];setActive(n);breadcrumbs([{text:c.title,href:link({chapter:n})},{text:x.q}]);const related=c.items.slice(Math.max(0,idx-2),idx).concat(c.items.slice(idx+1,idx+3));$('#view').innerHTML=`<article class="article"><span class="article-id">${esc(x.id)}・第 ${String(c.num).padStart(2,'0')} 章</span><h1>${esc(x.q)}</h1><div class="answer-card"><div class="answer-label">藥事照護回答</div><div class="answer-text">${esc(x.a)}</div></div><div class="article-actions"><a class="back-btn" href="${link({chapter:n})}">← 回本章目錄</a>${idx>0?`<a class="next-btn" href="${link({chapter:n,question:c.items[idx-1].id})}">上一篇</a>`:''}${idx<c.items.length-1?`<a class="next-btn" href="${link({chapter:n,question:c.items[idx+1].id})}">下一篇 →</a>`:''}</div>${related.length?`<section class="related"><h2>同章相關問題</h2><div class="question-list">${related.map(r=>`<a class="question-link" href="${link({chapter:n,question:r.id})}"><span class="question-id">${esc(r.id)}</span><span class="question-title">${esc(r.q)}</span><span class="question-arrow">›</span></a>`).join('')}</div></section>`:''}</article>`;bindInternal($('#view'))}
async function renderSearch(q){q=q.trim();setActive();breadcrumbs([{text:`搜尋：${q}`}]);$('#globalSearch').value=q;if(!q)return routeHome();const meta=await loadMeta();$('#view').innerHTML=`<section class="search-heading"><h1>搜尋「${esc(q)}」</h1><p id="searchStatus">正在搜尋全部 ${meta.chapters.length} 章…</p><div class="search-progress"><span id="progressBar" style="width:0"></span></div></section><div id="searchResults" class="search-results"></div>`;const results=[];const lower=q.toLowerCase();for(let i=0;i<meta.chapters.length;i++){const c=await loadChapter(meta.chapters[i].num);for(const x of c.items){const hay=(x.q+' '+x.a).toLowerCase();if(hay.includes(lower))results.push({...x,chapter:c.num,chapterTitle:c.title})}$('#progressBar').style.width=`${(i+1)/meta.chapters.length*100}%`;$('#searchStatus').textContent=`已搜尋 ${i+1} / ${meta.chapters.length} 章，暫時找到 ${results.length.toLocaleString()} 則`;}$('#searchStatus').textContent=`共找到 ${results.length.toLocaleString()} 則結果`;$('#progressBar').parentElement.remove();$('#searchResults').innerHTML=results.length?results.slice(0,500).map(r=>`<a class="result-item" href="${link({chapter:r.chapter,question:r.id})}"><small>第 ${String(r.chapter).padStart(2,'0')} 章・${esc(r.chapterTitle)}・${esc(r.id)}</small><h3>${esc(r.q)}</h3><p>${esc(r.a)}</p></a>`).join(''):`<div class="empty-state">找不到符合的內容。可嘗試較短的關鍵字，例如「血壓」、「退燒」、「抗生素」。</div>`;bindInternal($('#view'))}
async function route(){try{window.scrollTo(0,0);const p=params(),meta=await loadMeta();$('#chapterNav').innerHTML=navHtml(meta);$('.sidebar-footer span').textContent=`共 ${meta.chapters.length} 章・${meta.total.toLocaleString()} 則問答`;bindInternal($('#chapterNav'));if(p.get('q'))return renderSearch(p.get('q'));if(p.get('page'))return renderPage(p.get('page'),meta);if(p.get('chapter')&&p.get('question'))return renderQuestion(p.get('chapter'),p.get('question'));if(p.get('chapter'))return renderChapter(p.get('chapter'));renderHome(meta)}catch(e){console.error(e);$('#view').innerHTML=`<div class="empty-state"><h2>網站資料載入失敗</h2><p>${esc(e.message)}</p><button onclick="location.reload()">重新載入</button></div>`}}
function routeHome(){history.pushState({},'',location.pathname);route()}
window.addEventListener('popstate',route);
document.addEventListener('DOMContentLoaded',()=>{$('#searchForm').addEventListener('submit',e=>{e.preventDefault();const q=$('#globalSearch').value.trim();history.pushState({},'',link({q}));route()});$('#openNav').addEventListener('click',()=>document.body.classList.add('nav-open'));$('#closeNav').addEventListener('click',closeNav);$('#overlay').addEventListener('click',closeNav);$('#fontBtn').addEventListener('click',()=>{document.body.classList.toggle('large-text');localStorage.setItem('largeText',document.body.classList.contains('large-text')?'1':'0')});if(localStorage.getItem('largeText')==='1')document.body.classList.add('large-text');$('#shareBtn').addEventListener('click',async()=>{try{if(navigator.share)await navigator.share({title:document.title,url:location.href});else{await navigator.clipboard.writeText(location.href);$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1500)}}catch{}});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#globalSearch').focus()}});route()});
