(async()=>{
const $=s=>document.querySelector(s),content=$('#content'),nav=$('#chapters'),search=$('#search'),sel=$('#chapterSelect'),info=$('#resultInfo'),bar=$('#loadBar'),loadText=$('#loadText');
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function escapeRegExp(s){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function hi(s,q){if(!q)return esc(s);const e=escapeRegExp(q);return esc(s).replace(new RegExp(e,'ig'),m=>`<mark>${m}</mark>`)}
async function unpack(b64){const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));if(!('DecompressionStream'in window))throw new Error('此瀏覽器版本太舊，無法解壓縮網站資料。請改用最新版 Chrome、Safari 或 Edge。');const ds=new DecompressionStream('gzip');return JSON.parse(await new Response(new Blob([bytes]).stream().pipeThrough(ds)).text())}
try{
 const M=window.BOOK_META;const packs=window.CHAPTER_PACKS||{};if(!M||Object.keys(packs).length!==M.meta.chapters)throw new Error('網站資料檔未完整載入，請重新整理頁面。');
 const chapters=[];for(let i=0;i<M.chapters.length;i++){const m=M.chapters[i];loadText.textContent=`正在載入第 ${String(m.num).padStart(2,'0')} 章…`;chapters.push(await unpack(packs[m.num]));bar.style.width=`${Math.round((i+1)/M.chapters.length*100)}%`}
 const D={meta:M.meta,chapters};window.BOOK_DATA=D;$('#statQ').textContent=D.meta.questions.toLocaleString();$('#statC').textContent=D.meta.chapters;
 D.chapters.forEach(c=>{const o=document.createElement('option');o.value=c.num;o.textContent=`第 ${String(c.num).padStart(2,'0')} 章｜${c.title}`;sel.appendChild(o);const b=document.createElement('button');b.dataset.n=c.num;b.textContent=`${String(c.num).padStart(2,'0')}　${c.title}（${c.count}）`;b.onclick=()=>{sel.value=c.num;render();window.scrollTo({top:document.querySelector('.toolbar').offsetTop-70,behavior:'smooth'})};nav.appendChild(b)});
 function render(){const q=search.value.trim(),n=sel.value;content.innerHTML='';let shown=0;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',n&&b.dataset.n===n));D.chapters.filter(c=>!n||String(c.num)===n).forEach(c=>{const its=c.items.filter(x=>!q||(x.q+' '+x.a).toLowerCase().includes(q.toLowerCase()));if(!its.length)return;shown+=its.length;const h=document.createElement('div');h.className='chapter-head';h.innerHTML=`<h3>第 ${String(c.num).padStart(2,'0')} 章　${esc(c.title)}</h3><p>${its.length} 則符合內容</p>`;content.appendChild(h);its.forEach(x=>{const a=document.createElement('article');a.className='qa';a.innerHTML=`<div class="question"><span class="qid">${esc(x.id)}</span><span>${hi(x.q,q)}</span></div><div class="badges">${x.risk?'<span class="badge risk">涉及用藥決策，請先詢問專業人員</span>':''}${x.review?'<span class="badge review">可能需依最新指引重新確認</span>':''}</div><div class="answer">${hi(x.a,q)}</div>`;a.querySelector('.question').onclick=()=>a.classList.toggle('open');if(q)a.classList.add('open');content.appendChild(a)})});info.textContent=q||n?`找到 ${shown.toLocaleString()} 則內容`:`共 ${D.meta.questions.toLocaleString()} 則問答；點選問題即可展開答案。`;if(!shown)content.innerHTML='<div class="empty">找不到相符內容。可改用較短關鍵字，例如搜尋「血壓」而不是完整句子。</div>'}
 search.addEventListener('input',render);sel.addEventListener('change',render);$('#clearBtn').onclick=()=>{search.value='';sel.value='';render()};$('#fontBtn').onclick=()=>document.body.classList.toggle('large-text');render();
}catch(e){content.innerHTML=`<div class="loading-error"><strong>網站載入失敗</strong><p>${esc(e.message)}</p></div>`;console.error(e)}
const toast=$('#toast');function flash(){toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1600)}
async function copyUrl(){try{await navigator.clipboard.writeText(location.href);flash()}catch{prompt('請複製以下網址：',location.href)}}
$('#copyBtn').onclick=copyUrl;$('#shareBtn').onclick=async()=>{if(navigator.share){try{await navigator.share({title:document.title,text:'民眾藥安心・藥師藥關心：可搜尋的社區用藥照護問答',url:location.href})}catch(e){if(e.name!=='AbortError')copyUrl()}}else copyUrl()};
})();